spring.application.name=cms
spring.profiles.active=local

#in sviluppo update in prod none
spring.jpa.hibernate.ddl-auto=update
#in sviluppo mostra le query in console, in prod none
spring.jpa.show-sql=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

server.port=8080